// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTrsI8ddhFe57vaLsMGFJ8bLAcDHR9DCc',
    appId: '1:523641979067:web:c4d2ac5fc7930bd728e99e',
    messagingSenderId: '523641979067',
    projectId: 'filmfreak',
    authDomain: 'filmfreak.firebaseapp.com',
    storageBucket: 'filmfreak.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIANgHmFI_eCRRmzDGeI5wFJqtxVRn5tY',
    appId: '1:523641979067:android:df8b1c5b56064c6428e99e',
    messagingSenderId: '523641979067',
    projectId: 'filmfreak',
    storageBucket: 'filmfreak.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNyw2pecyH2B6ixQ5GOFv1XhsFKVm-2Vw',
    appId: '1:523641979067:ios:3976628891edee6328e99e',
    messagingSenderId: '523641979067',
    projectId: 'filmfreak',
    storageBucket: 'filmfreak.appspot.com',
    iosClientId: '523641979067-v0h0cabp6e13i7fonqpqas9mvflj177o.apps.googleusercontent.com',
    iosBundleId: 'com.example.startupNamer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNyw2pecyH2B6ixQ5GOFv1XhsFKVm-2Vw',
    appId: '1:523641979067:ios:3976628891edee6328e99e',
    messagingSenderId: '523641979067',
    projectId: 'filmfreak',
    storageBucket: 'filmfreak.appspot.com',
    iosClientId: '523641979067-v0h0cabp6e13i7fonqpqas9mvflj177o.apps.googleusercontent.com',
    iosBundleId: 'com.example.startupNamer',
  );
}
